---
title: "Code sections to add"
author: "Molly Leavens"
date: "6/17/2021"
output: pdf_document
---

```{r}
library(tidyverse)

 p1 <- ggplot(mtcars) +
geom_point(aes(x = wt, y = mpg, colour = gear)) +
labs(
title = "Fuel economy declines as weight increases",
subtitle = "(1973-74)",
caption = "Data from the 1974 Motor Trend US magazine.",
tag = "Figure 1",
x = "Weight (1000 lbs)",
y = "Fuel economy (mpg)",
colour = "Gears"
)

p1 + theme_gray() # the default
#The signature ggplot2 theme with a grey background and white gridlines,
#' designed to put the data forward yet make comparisons easy.
p1 + theme_bw()
#The classic dark-on-light ggplot2 theme. May work better for presentations
#' displayed with a projector.
p1 + theme_linedraw()
#A theme with only black lines of various widths on white backgrounds,
#' reminiscent of a line drawing. Serves a purpose similar to `theme_bw()`.
#' Note that this theme has some very thin lines 
p1 + theme_light()
#A theme similar to `theme_linedraw()` but with light grey lines and axes,
#' to direct more attention towards the data.
p1 + theme_dark()
#The dark cousin of `theme_light()`, with similar line sizes but a dark background. Useful to make thin coloured lines pop out.
p1 + theme_minimal()
#A minimalistic theme with no background annotations.}
p1 + theme_classic()
#A classic-looking theme, with x and y axis lines and no gridlines

```

## Other aestetics

```{r}
THEMES: HORIZONTAL GRID LINES? YES, NO. 

LIGHT GRAY OR WHITE BACKGROUND?

## Example dataset
  
  
```


## With mean and median
```{r,}
df %>%
  # Set x-axis to key variable
  ggplot(aes(x = total_hh_income), fill = dataset) +
  # Add density line. You can change the fill and line colors.
  # geom_area(aes(y = ..density..), stat ="bin", binwidth = 500) +
  # geom_freqpoly(aes(y = ..density..))+
  # geom_density(color = "#add8e6", fill = "#add8e6", bw=8000) +
  # stat_bin(geom = "area") +
  geom_histogram(aes(y =(..count..)/sum(..count..))) +
  # Add vertical line for living income
  geom_vline(aes(xintercept = mean(benchmark), 
                 color = "Living Income Benchmark"), key_glyph = "path") +
  # Add vertical line for mean income 
  geom_vline(aes(xintercept = mean(df$total_hh_income), 
                 color = "Income Mean"), key_glyph = "path") +
  # Add vertical line for median income
  geom_vline(aes(xintercept = median(df$total_hh_income), 
                 color = "Income Median"), key_glyph = "path") +
  # Add graph and axis labels
  labs(x = paste("Estimated Total Household Income (", 
                 currency, "/", "year/household)", 
                 sep = ""),
       y = "Proportion of households",
# Add caption with observation numbers for each household type             
       caption = paste("N =", nrow(df), ", bin size = ", 
                       "BINSIZE", collapse = '')) +
  # Format x-axis labels as numbers with commas
  # If your data has extreme income outliers, 
    # you may need to filter them or add x-axis limits so they do not warp the graph 
  scale_x_continuous(labels = comma) +
  scale_y_continuous(labels = percent) +
  # Remove y-axis labels and ticks
  theme(#axis.text.y = element_blank(), axis.ticks.y = element_blank(),
  # Remove background grid (the grid is the default)
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  # Move the legend to the bottom of the graph
        legend.position="bottom",
  # Remove legend title
        legend.title = element_blank(),
  # Remove gray background for legend symbols 
        legend.key=element_rect(fill=NA),
  # Put a box around the legend
        legend.box.background = element_rect(),
  # Move caption to desired location
        plot.caption = element_text(hjust = 0)) +
  # Manually add legend 
  scale_color_manual(values = c("Living Income Benchmark"= "red",
                                "Income Mean"= "blue",
                                "Income Median"="green"))
```